name: Deploy stackit/server
on:
    workflow_dispatch:

    pull_request:
        branches:
            - main
env:
    STACKIT_TF_ENABLE_BETA_RESOURCES: true

jobs:
    terraform_plan:
        name: "terraform plan"
        runs-on: ubuntu-latest
        steps:
            - name: "checkout repo"
              uses: actions/checkout@v4
            - name: "install terraform"
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "1.11.1"
            - name: "terraform init"
              run: terraform init
              working-directory: "cloud/stackit/server/terraform"
              env:
                  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
                  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}